services:
  db:
    image: postgres:16
    container_name: uangku_db
    restart: always
    environment:
      POSTGRES_USER: ihab
      POSTGRES_PASSWORD: apayhh
      POSTGRES_DB: finance_uangku
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: uangku_api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgresql://ihab:apayhh@db:5432/finance_uangku
    depends_on:
      - db
